export type LengthUnit='in'|'ft'|'cm'|'m';export type VolumeUnit='ft3'|'yd3'|'liter'|'dryQuart'|'gallon';export type BagUnit=VolumeUnit|'lb'|'kg';
export const FT3_PER_YD3=27,LITERS_PER_FT3=28.316846592,DRY_QUARTS_PER_FT3=25.71404638,GALLONS_PER_FT3=7.48051948,FT3_PER_GALLON=0.133680556;
export function lengthToFeet(v:number,u:LengthUnit){if(!Number.isFinite(v))return 0;return u==='ft'?v:u==='in'?v/12:u==='cm'?v/30.48:v*3.280839895}
export function volumeToFt3(v:number,u:VolumeUnit|BagUnit){if(!Number.isFinite(v)||v<=0)return 0;if(u==='ft3')return v;if(u==='yd3')return v*27;if(u==='liter')return v/LITERS_PER_FT3;if(u==='dryQuart')return v/DRY_QUARTS_PER_FT3;if(u==='gallon')return v*FT3_PER_GALLON;return 0}
export const yd3=(v:number)=>v/27,liters=(v:number)=>v*LITERS_PER_FT3,dryQt=(v:number)=>v*DRY_QUARTS_PER_FT3,gallons=(v:number)=>v*GALLONS_PER_FT3;
export interface VolumeResult{baseVolumeFt3:number;finalVolumeFt3:number;volumeYd3:number;volumeLiters:number;volumeDryQuarts:number;volumeGallons:number;warnings:string[]}
export function volumeResult(base:number,final=base,warnings:string[]=[]):VolumeResult{return{baseVolumeFt3:base,finalVolumeFt3:final,volumeYd3:yd3(final),volumeLiters:liters(final),volumeDryQuarts:dryQt(final),volumeGallons:gallons(final),warnings}}
export interface RaisedBedInput{length:number;width:number;depth:number;lengthUnit:LengthUnit;widthUnit:LengthUnit;depthUnit:LengthUnit;numberOfBeds:number;freeboard:number;freeboardUnit:LengthUnit;settlingAllowancePercent:number}
export function calculateRaisedBedVolume(i:RaisedBedInput){const w:string[]=[];if(i.depthUnit==='ft'&&i.depth>3)w.push('Depth is entered in feet and looks unusually deep. Did you mean inches?');if(i.depthUnit==='in'&&i.depth>36)w.push('Depth is over 36 inches. Check the unit.');if(i.settlingAllowancePercent>30)w.push('Settling allowance above 30% is unusual; most estimates use 10–15%.');const d=Math.max(lengthToFeet(i.depth,i.depthUnit)-lengthToFeet(i.freeboard,i.freeboardUnit),0),base=lengthToFeet(i.length,i.lengthUnit)*lengthToFeet(i.width,i.widthUnit)*d*Math.max(1,Math.floor(i.numberOfBeds||1));return volumeResult(base,base*(1+Math.max(0,i.settlingAllowancePercent||0)/100),w)}
export interface SoilBagInput{bagSize:number;bagUnit:BagUnit;bagPrice?:number}export function calculateSoilBags(requiredVolumeFt3:number,i:SoilBagInput){const warnings:string[]=[];if(i.bagUnit==='lb'||i.bagUnit==='kg')warnings.push('Weight-based soil bags are only rough estimates because soil density varies. Use package volume when possible.');const bagVolumeFt3=volumeToFt3(i.bagSize,i.bagUnit);if(requiredVolumeFt3<=0||bagVolumeFt3<=0)return{bagVolumeFt3,rawBags:0,bagsNeeded:0,leftoverFt3:0,totalCost:i.bagPrice?0:undefined,warnings};const rawBags=requiredVolumeFt3/bagVolumeFt3,bagsNeeded=Math.ceil(rawBags);return{bagVolumeFt3,rawBags,bagsNeeded,leftoverFt3:bagsNeeded*bagVolumeFt3-requiredVolumeFt3,totalCost:i.bagPrice===undefined?undefined:bagsNeeded*i.bagPrice,warnings}}
export function compareBulkVsBags(requiredVolumeFt3:number,bag:SoilBagInput,bulk:{pricePerCubicYard:number;deliveryFee:number;minimumOrderYards:number}){const b=calculateSoilBags(requiredVolumeFt3,bag),bagTotalCost=b.totalCost??0,requiredYd3=requiredVolumeFt3/27,bulkOrderYd3=Math.max(requiredYd3,Math.max(0,bulk.minimumOrderYards)),bulkTotalCost=bulkOrderYd3*Math.max(0,bulk.pricePerCubicYard)+Math.max(0,bulk.deliveryFee),savings=bagTotalCost-bulkTotalCost,overbuyFt3=bulkOrderYd3*27-requiredVolumeFt3,w=[...b.warnings];if(requiredVolumeFt3<10)w.push('For small volumes under 10 ft³, bagged soil is often more practical.');if(overbuyFt3>requiredVolumeFt3)w.push('Your minimum bulk order is much larger than the required volume.');if(bulk.deliveryFee>bulkOrderYd3*bulk.pricePerCubicYard&&bulk.deliveryFee>0)w.push('Delivery costs more than the soil itself.');return{bagTotalCost,bulkTotalCost,requiredYd3,bulkOrderYd3,bagCostPerFt3:bag.bagPrice&&b.bagVolumeFt3?bag.bagPrice/b.bagVolumeFt3:0,bulkCostPerFt3:bulkOrderYd3?bulkTotalCost/(bulkOrderYd3*27):0,savings,overbuyFt3,recommendation:savings>.01?'bulk':savings<-.01?'bags':'tie' as 'bulk'|'bags'|'tie',warnings:w}}
export interface MixComponent{id:string;name:string;ratioPercent:number;bagSize?:number;bagUnit?:BagUnit;bagPrice?:number}export function calculateSoilMix(totalVolumeFt3:number,input:{templateId:string;components:readonly MixComponent[]}){const sum=input.components.reduce((t,c)=>t+c.ratioPercent,0),warn:string[]=[];if(input.components.some(c=>c.ratioPercent<0))warn.push('Soil mix percentages cannot be negative.');if(Math.abs(sum-100)>.01)warn.push('Soil mix percentages must add up to 100%.');if(input.components.some(c=>/compost|manure/i.test(c.name)&&c.ratioPercent>50))warn.push('Compost or manure above 50% may not suit all crops.');return input.components.map(c=>{const v=warn.length?0:totalVolumeFt3*c.ratioPercent/100,b=c.bagSize&&c.bagUnit?calculateSoilBags(v,{bagSize:c.bagSize,bagUnit:c.bagUnit,bagPrice:c.bagPrice}):undefined;return{componentId:c.id,name:c.name,ratioPercent:c.ratioPercent,volumeFt3:v,volumeYd3:v/27,volumeLiters:liters(v),bagsNeeded:b?.bagsNeeded,cost:b?.totalCost,warnings:[...warn,...(b?.warnings??[])]}})}
export function calculateGrowBagVolume(i:{gallons:number;quantity:number}){return volumeResult(Math.max(0,i.gallons)*FT3_PER_GALLON*Math.max(1,Math.floor(i.quantity||1)),undefined,['Grow bag listed capacity and real filled volume can vary by brand and fill level.'])}
export function calculateRectangularPlanterVolume(i:{length:number;width:number;depth:number;unit:LengthUnit;quantity:number}){return volumeResult(lengthToFeet(i.length,i.unit)*lengthToFeet(i.width,i.unit)*lengthToFeet(i.depth,i.unit)*Math.max(1,Math.floor(i.quantity||1)))}
export function calculateRoundPotVolume(i:{diameter:number;height:number;unit:LengthUnit;quantity:number}){const r=lengthToFeet(i.diameter,i.unit)/2;return volumeResult(Math.PI*r*r*lengthToFeet(i.height,i.unit)*Math.max(1,Math.floor(i.quantity||1)))}
export function calculateTaperedPotVolume(i:{topDiameter:number;bottomDiameter:number;height:number;unit:LengthUnit;quantity:number}){const r1=lengthToFeet(i.topDiameter,i.unit)/2,r2=lengthToFeet(i.bottomDiameter,i.unit)/2,h=lengthToFeet(i.height,i.unit);return volumeResult(Math.PI*h/3*(r1*r1+r1*r2+r2*r2)*Math.max(1,Math.floor(i.quantity||1)))}
export function calculateAnnualTopOff(i:{length:number;width:number;topOffDepth:number;lengthUnit:LengthUnit;widthUnit:LengthUnit;topOffDepthUnit:LengthUnit;numberOfBeds:number}){return volumeResult(lengthToFeet(i.length,i.lengthUnit)*lengthToFeet(i.width,i.widthUnit)*lengthToFeet(i.topOffDepth,i.topOffDepthUnit)*Math.max(1,Math.floor(i.numberOfBeds||1)))}
export interface Crop{id:string;name:string;plantsPerSquareFoot:number|[number,number];minDepthInches?:number;idealDepthInches?:[number,number];notes:string;warning?:string}
export const CROPS:Crop[]=[{id:'tomato',name:'Tomato',plantsPerSquareFoot:1,minDepthInches:12,idealDepthInches:[12,24],notes:'Use a cage or trellis.',warning:'Large tomato varieties may need more than one square foot.'},{id:'pepper',name:'Pepper',plantsPerSquareFoot:1,minDepthInches:10,idealDepthInches:[12,18],notes:'One plant per square foot is conservative.'},{id:'cucumber',name:'Cucumber',plantsPerSquareFoot:[1,2],minDepthInches:8,idealDepthInches:[10,18],notes:'Trellis for tighter spacing.'},{id:'lettuce',name:'Lettuce',plantsPerSquareFoot:[2,4],minDepthInches:6,idealDepthInches:[6,8],notes:'Baby leaf vs full head changes spacing.'},{id:'spinach',name:'Spinach',plantsPerSquareFoot:9,minDepthInches:6,idealDepthInches:[6,8],notes:'Common square-foot estimate.'},{id:'carrot',name:'Carrot',plantsPerSquareFoot:[9,16],minDepthInches:8,idealDepthInches:[10,12],notes:'Short varieties need less depth.'},{id:'radish',name:'Radish',plantsPerSquareFoot:16,minDepthInches:6,idealDepthInches:[6,8],notes:'Fast dense crop.'},{id:'basil',name:'Basil',plantsPerSquareFoot:[1,4],minDepthInches:6,idealDepthInches:[8,12],notes:'Depends on harvest style.'},{id:'beans',name:'Beans',plantsPerSquareFoot:[4,9],minDepthInches:8,idealDepthInches:[8,12],notes:'Bush and pole beans differ.'},{id:'kale',name:'Kale',plantsPerSquareFoot:1,minDepthInches:8,idealDepthInches:[10,12],notes:'Large leaves need room.'}];
export function calculateSquareFootSpacing(i:{lengthFt:number;widthFt:number;cropId:string;customPlantsPerSquare?:number}){const totalSquares=Math.max(0,Math.floor(i.lengthFt)*Math.floor(i.widthFt)),crop=CROPS.find(c=>c.id===i.cropId),pps=i.customPlantsPerSquare||crop?.plantsPerSquareFoot||1,totalPlants=Array.isArray(pps)?[Math.floor(totalSquares*pps[0]),Math.floor(totalSquares*pps[1])] as [number,number]:Math.floor(totalSquares*pps);return{totalSquares,plantsPerSquareFoot:pps,totalPlants,crop,warning:crop?.warning}}
export function checkDepthSuitability(depthInches:number,cropId:string){const crop=CROPS.find(c=>c.id===cropId);if(!crop)return depthInches>=12?{status:'good',message:'This depth is generally workable for many raised bed crops.'}:depthInches>=6?{status:'borderline',message:'This can work for shallow greens and herbs.'}:{status:'notIdeal',message:'This is shallow for most raised bed crops.'};const min=crop.minDepthInches??6,ideal=crop.idealDepthInches;if(ideal&&depthInches>=ideal[0])return{status:'good',message:`${crop.name} is generally suitable at this depth as a planning estimate.`,recommendedDepthRange:ideal};if(depthInches>=min)return{status:'borderline',message:`${crop.name} may work, but a deeper bed is usually safer.`,recommendedDepthRange:ideal};return{status:'notIdeal',message:`${crop.name} usually needs more depth than this.`,recommendedDepthRange:ideal}}
export const RAISED_BED_PRESETS=[6,8,10,12,18,24];export const BAG_PRESETS=[['40 dry qt',40,'dryQuart'],['1 cu ft',1,'ft3'],['1.5 cu ft',1.5,'ft3'],['2 cu ft',2,'ft3'],['3 cu ft',3,'ft3'],['50 L',50,'liter']] as const;
export const MIXES={basic:{templateId:'basic',components:[{id:'topsoil',name:'Topsoil',ratioPercent:60},{id:'compost',name:'Compost',ratioPercent:30},{id:'pottingMix',name:'Potting mix',ratioPercent:10}]},soilless:{templateId:'soilless',components:[{id:'compost',name:'Compost',ratioPercent:50},{id:'soillessMix',name:'Soilless mix',ratioPercent:50}]},melsMix:{templateId:'melsMix',components:[{id:'compost',name:'Blended compost',ratioPercent:33.33},{id:'coir',name:'Peat moss or coco coir',ratioPercent:33.33},{id:'vermiculite',name:'Vermiculite or perlite',ratioPercent:33.34}]},budgetFill:{templateId:'budgetFill',components:[{id:'lower',name:'Lower filler material',ratioPercent:40},{id:'topsoil',name:'Topsoil',ratioPercent:35},{id:'compost',name:'Compost',ratioPercent:25}]}} as const;
export function fmt(n:number,d=2){return Number.isFinite(n)?Math.round((n+Number.EPSILON)*10**d)/10**d:0}export function plantText(v:number|[number,number]){return Array.isArray(v)?`${v[0]}–${v[1]}`:`${v}`}
