import assert from 'node:assert/strict';
import fs from 'node:fs';
const read = (file) => fs.readFileSync(file, 'utf8');
const pages = read('src/lib/data/pages.ts');
const slugPage = read('src/app/[slug]/page.tsx');
const home = read('src/app/page.tsx');
const sitemap = read('src/app/sitemap.ts');
const ads = read('src/components/AdSenseAutoAds.tsx');
const calculator = read('src/components/Calculator.tsx');
const slugs = [...pages.matchAll(/slug: '([^']+)'/g)].map((m) => m[1]);
assert.equal(new Set(slugs).size, 70, 'All 70 existing routes must remain.');
assert.ok(slugPage.indexOf('<Calculator') < slugPage.indexOf('tool-page-intro'), 'Tool must appear before descriptive hero on calculator pages.');
assert.ok(home.indexOf('<Calculator') < home.indexOf('tool-page-intro'), 'Homepage must be tool-first.');
assert.ok(!slugPage.includes('<AdSlot') && !slugPage.includes('<AffiliateSlot'), 'Calculator pages must not contain blank ad/affiliate placeholders.');
assert.ok(!calculator.includes('<AdSlot'), 'Result area must not contain a blank ad slot.');
assert.ok(pages.includes('isIndexableSlug(page.slug)'), 'Metadata must apply index/noindex policy.');
assert.ok(sitemap.includes('.filter((page) => isIndexableSlug(page.slug))'), 'Sitemap must include only approved pages.');
assert.ok(ads.includes('isAdsenseAllowedPath'), 'AdSense must use explicit route allowlist.');
console.log('BedSoil audit passed: 70 routes preserved; tool-first layout, noindex preset policy, sitemap filtering, and AdSense allowlist enforced.');
